# Buildpack API version
api = "0.10"

# Extension ID and metadata
[extension]
id = "custom-extension/audiowaveform"
version = "0.0.1"
name = "Add BBC Audiowaveform and FFMPEG"
homepage = "https://github.com/a1flecke/buildpacks-examples"
description = "Proof of concept"
