description = "Tiny base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.20.1"

[build]
image = "a1flecke/builder-build-image-with-yarn"

[run]
[[run.images]]
image = "index.docker.io/paketobuildpacks/run-jammy-tiny:latest"
mirrors = []

[[targets]]
  arch = "x86-64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"