description = "Tiny base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.20.1"

[build]
image = "a1flecke/my-builder-builder"

[run]
[[run.images]]
image = "a1flecke/my-builder-run"
mirrors = []

[[targets]]
  arch = "x86-64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"