description = "Tiny base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.20.0"

[stack]
  build-image = "a1flecke/builder-build-image-with-yarn"
  id = "io.buildpacks.stacks.jammy.tiny"
  run-image = "paketobuildpacks/run-jammy-tiny:0.2.46"
  run-image-mirrors = []

[[targets]]
  arch = "x86-64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"